### ISSUE TITLE
HTTP error code

### ISSUE THREAD

**Issue by seaneble** [DavidHavl/DhErrorLogging#10]
Hello David,

first of all: Thanks for the module! This saves me a lot of work.

I noticed that the fatal error page is delivered to the client with a HTTP status code of 200. I would much prefer this to be something adequate (possible 500). What would you think? Send a static header or rather make it configurable? I could also try to create an appropriate pull request.

Sebastian

**Comment by DavidHavl** [comment]
Hi Sebastian,

the fatal and normal errors do send 500 status code. You just need to set the PHP display_errors setting for your application to off:
 ini_set('display_errors',0);

**Comment by seaneble** [comment]
Did you delete your last comment?

**Comment by DavidHavl** [comment]
Yes it was not really relevant any more since the issue with status code 200 is only on development machines where display_errors is on.
Dealing with it for this scenario would mean a big overhead and intervention into the overall application system. This is because if "display_errors" is "on" the PHP sends output to the screen before we can intercept, so the solution would have to be: to have 500 status code as default for all responses and change it for any successful response just before going out. It is doable but not sensible in my opinion.
